compatibility_date = "2022-01-01"
type = "javascript"
workers_dev = false

name = "clip-local"
vars = { ENVIRONMENT = "local" }
kv_namespaces = [{ binding = "DB", id = "" }]

[env.production]
name = "clip"
vars = { ENVIRONMENT = "production" }
kv_namespaces = [{ binding = "DB", id = "" }]

[build]
command = "npm run build"
watch_dir = "src"

[build.upload]
format = "service-worker"

[site]
bucket = "./public"
entry-point = "."

[miniflare]
host = "localhost"
port = 3000
kv_persist = true
