compatibility_date = "2023-03-01"

name = "clip-batch"
main = "./src/index.ts"

workers_dev = false

[triggers]
crons = ["0 0 * * sun"]

[[kv_namespaces]]
binding = "KV_CLIP"
id = "ef6ddb45fac643a4847ba5e6dd888a9d"         # clip
preview_id = "adf3c5007b954bc189c1f0909bbea0ac" # test

[dev]
port = 2999
