export const ErrorCode = {
  E_FAILED_GET_ALL_FROM_KV: 'E_FAILED_GET_ALL_FROM_KV',
  E_FAILED_ADD_ONE_TO_KV: 'E_FAILED_ADD_ONE_TO_KV',
  E_FAILED_REMOVE_ONE_FROM_KV: 'E_FAILED_REMOVE_ONE_FROM_KV',
  E_FAILED_FETCH_PAGEDATA: 'E_FAILED_FETCH_PAGEDATA',
  E_BAD_REQUEST_BODY_ON_ADD: 'E_BAD_REQUEST_BODY_ON_ADD',
  E_BAD_REQUEST_BODY_ON_REMOVE: 'E_BAD_REQUEST_BODY_ON_REMOVE',
  E_GET_ASSET_FROM_KV: 'E_GET_ASSET_FROM_KV',
  E_UNKNOWN: 'E_UNKNOWN',
} as const
