name: check

on: push

permissions:
  contents: read

env:
  CI: true
  TZ: Asia/Tokyo

jobs:
  all:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.node-version'
      - run: npm ci
      - run: npm run lint
  app:
    needs: [all]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.node-version'
      - run: npm ci
      - run: npm run build
  extension:
    needs: [all]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.node-version'
      - run: npm ci
      - run: npm run build:extension
