name: deploy-batch

on:
  push:
    branches:
      - main
    paths:
      - 'batch/**'
      - 'package-lock.json'
  workflow_dispatch:

permissions:
  contents: read

env:
  CI: true
  TZ: Asia/Tokyo

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: .node-version
      - run: npm ci
      - uses: cloudflare/wrangler-action@v3.1.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          workingDirectory: 'batch'
